### ISSUE TITLE
Doesn't have OpenGL/Vulkan Natives 

### ISSUE THREAD

**Issue by 072608** [DethRaid/nova-renderer#1]
"net.minecraftforge.fml.common.LoaderException: java.lang.UnsatisfiedLinkError: no /libvulkan-mod-native in java.library.path"

I do realize this is in pre-alpha state but I'd like to give it a try, so could you provide the natives it needs 
thanks
[crash-2016-05-08_12.20.16-client.txt](https://github.com/DethRaid/nova-renderer/files/253995/crash-2016-05-08_12.20.16-client.txt)

**Comment by DethRaid** [comment]
So, a few things.

First, I've just pushed a major update. I switched from Forge to MCP because Forge wasn't loading my libraries correctly. I switched from Vulkan to OpenGL 4.5 because Vulkan is complicated and OpenGL is way easier to set up.

Second, this project is in no way ready for use. Currently, all it does is create a texture atlas from Minecraft's textures and send them to the native code, and create a window from the native code. If you run it, you'll be disappointed.

Third, I don't want to provide binaries because they're large and don't work well with Git and providing binaries implies some sort of release, and this code is no where near release. However, you can build the binaries yourself. The C++ code is structured in a CMake project, so you can use that to generate build files for your favorite C++ compiler, then compile the libraries yourself.

However, even that won't get the code to run. I've made a few changes to the MC source code to add in hooks for my code, but I haven't pushed those to this repository because the Minecraft and MCP licenses definitely forbid distributing Minecraft's source code. When this software is closer to release, I'll make a nice installer to perform my changes on Minecraft itself, but until then you'll have to try to follow my changes in the [changes file](https://github.com/DethRaid/nova-renderer/blob/master/src/minecraft/docs/changes.txt).

**Comment by 072608** [comment]
Oh, ok I was just wondering , I didn't know if it was in running state or not , someone linked this on a Reddit post , and I wanted to test out performance differences , but I guess I'm bit too early to party. I'll keep following project , and see where it goes cause Minecraft needs a newer render cause OpenGL 2.1 is very old dated  ( Also I'm not huge into coding but I could see problems using Vulkan since its brand new and its not documented that well ). But like I said sorry if I bothered you , I just wanted to see if I could test it

**Comment by DethRaid** [comment]
Sorry, it's just too early in development to have anything worth showing.
