### ISSUE TITLE
DirectX Support?

### ISSUE THREAD

**Issue by deprilula28** [DethRaid/nova-renderer#10]
I love the idea of the mod, but if performance is key, most hardware support DirectX and Direct3D up to 9-11, and it's so much better for that purpose. I get OpenGL is way more widely supported, but I think the development time that would be put onto Direct3D support would pay off the performance.

(This is not an issue, but "Issues" it's the best place I've found to suggest stuff, as used one guy in one of my projects)

**Comment by mdsitton** [comment]
The opengl version that dethraid is targeting will probably lessen the number of devices that are supported over all. So far cutting Mac OSX out completely.

But don't let old, slow, and badly optimized opengl applications fool you. OpenGL can have great performance that even surpasses directx if it's done properly. There have been very few applications written that take full advantage of opengl 4.5.

OpenGL at 4.5 is a very different api from even opengl 3.3, and a long way from the opengl 2.1 that minecraft uses.

And finally there is nothing really preventing multiple rendering apis from having their own renderer backends. OpenGL 4.5 comes first. Vulkan will probably be next if any other api is to be used. After that I would probably like to see metal looked at for Mac OSX. With opengl and vulkan I really don't see the need for DirectX, even if it would be possible.

But this is just my opinion, I have been trying to contribute with fixes but ultimately the decisions lie with dethraid.

**Comment by deprilula28** [comment]
About the new versions of OpenGL, I didn't know it could really get at the level of DirectX. I still hold that if both are optimized well DirectX will win performance-wise, but DX doesn't need that much optimization.

I didn't know about vulkan before, and it really looks like a big step in performance, even though it leaves the red team behind.
Metal is only good for iOS, since that has 42% of the mobile market, but Macs are a very minor part of the industry these days. You wouldn't want to play Minecraft in it anyway, so I think this project doesn't need to go onto Metal.

Overall, I'm pretty sure I regret saying DirectX being that much better, mainly because how horribly unoptimized the entire game is, and game code needs to be ran before any rendering happends, so I'm pretty sure that at the level of percentage getting DirectX (or vulkan for that matter) it will get very affected by the single-threaded java game code.

**Comment by mdsitton** [comment]
Here is one example of opengl 4.5 level features(4.4 actually) being way faster than directx 11: http://imgur.com/2mZBKhq

Though a very synthetic example using point sprites, it still something...
that is a screenshot from this presentation: http://media.steampowered.com/apps/steamdevdays/slides/beyondporting.pdf

**Comment by PaintNinja** [comment]
Shouldn't we be comparing DX12 with OpenGL 4.5? I heard the performance differences between DX11 and 12 are significant due to it being much more CPU efficient - especially on high-core systems like AMD FX CPUs

**Comment by deprilula28** [comment]
DirectX 12 is supported by a very minor amount of gpus and from what I've heard has is harder to program in. I don't think it would be a very good idea going into DX 12, mostly because there isn't that big of a performance boost (only CPU, but OGL 4.5 and DX11 don't use that much anyway).

**Comment by mdsitton** [comment]
DX12 should be compared the Vulkan, DX11.3 should be compared to OpenGL 4.5ish i'd say.

**Comment by mdsitton** [comment]
Also the way opengl is those 4.5 level features are also extensions. So persistently mapped buffers as used in that benchmark. Can be used all the way back to opengl 4.3 so if one had a driver that didnt support 4.5 but did support that extension, you would get similar performance gains.

**Comment by dotModded** [comment]
Okay so hopefully this will end this discussion, OpenGL  4.5 is very fast and removes a lot of overhead on the CPU end if programmed correctly making it faster than DX11.X no matter what. DX12 is a low level language as is vulkan, these languages are far harder to understand and write because you have to do everything yourself, both of these have the capability of being extremely fast, however to be fast they need to be written very very well and most of the time unless you know everything a driver normally does, your renderer wont be fast, this is why we chose OpenGL 4.5 over vulkan at least for now. 

Opengl is very robust if you code using AZDO allowing it to actually becoming almost as fast as vulkan in most cases. DX is very limited on hardware and will be more difficult to adopt shaders from the existing community. So we chose OpenGL 4.5 over all the rest as it makes the most sense.

**Comment by DethRaid** [comment]
mdsitton and dotmodded have explained our decision to use OpenGL 4.5 very well. There's nothing inherently faster about DirectX 11, and an OpenGL 4.5 application which takes full advantage of OpenGL 4.5's features can be significantly faster DirectX 11. There are currently no plans to support DirectX, mostly because I don't see us gaining anything that OpenGL 4.5 doesn't provide.
